### ISSUE TITLE
Add more packages to "licensed" installers

### ISSUE THREAD

**Issue by jahirfiquitiva** [javiersantos/PiracyChecker#1]
In my app, I used a similar method to check the app that installed my app, the allowed packages were:

"com.google.android.feedback"
"com.android.vending"

Any of these 2 options mean app was installed from Play Store

"com.amazon.venezia"

This the package for Amazon App Store.

I would do a Pull Request, but I wouldn't like to do it just for these minor things.

Hope they can be added soon, so I can start implementing this awesome library.

Thank you Javier. Keep up the good work.

**Comment by javiersantos** [comment]
The latest update includes support for the Amazon App Store. `com.google.android.feedback` has been added to the Google Play installer id too https://github.com/javiersantos/PiracyChecker/commit/3345f04d6fd4b0fb1086562245f93b4b1f7d1ebd

Thank you!

```xml
dependencies {
       compile 'com.github.javiersantos:PiracyChecker:0.0.2'
}
```

**Comment by jahirfiquitiva** [comment]
I would suggest making Amazon Apps Store an option, like something you can enable or not.

Some people may not want their apps published on Amazon Apps Store and some may do.

**Comment by javiersantos** [comment]
It's optional. You have to pass the allowed stores using the builder.

```Java
.enableInstallerId(InstallerID.GOOGLE_PLAY)
.enableInstallerId(InstallerID.AMAZON_APP_STORE)
```

**Comment by jahirfiquitiva** [comment]
Uh, nice. Thank you 🙂
