### ISSUE TITLE
Add Lucky Patcher Detection Based on Provider in manifest

### ISSUE THREAD

**Issue by apkunpacker** [javiersantos/PiracyChecker#102]

**Comment by jahirfiquitiva** [comment]
do you think you could create a pull request with this feature?

**Comment by apkunpacker** [comment]
> do you think you could create a pull request with this feature?

I don't think i can because i am not java developer . i only know how these tools works and can be defeated/detected properly

**Comment by TimScriptov** [comment]
> do you think you could create a pull request with this feature?

Hello. My friend and I developed this script a year ago. I do not recommend using it! It works for a very long time, the check can take several minutes.

See also filtering by package name startSwith ("ru)" does not optimize the code.

**Comment by TimScriptov** [comment]
And also this script was published without my permission! I shared it with ApkRepaker for private use, not for publication.

I would not like the LP developer to close the hole in his code
