### ISSUE TITLE
And to remove?

### ISSUE THREAD

**Issue by Joseiltonslv** [javiersantos/PiracyChecker#105]
For example I have an app, which previously worked but now gives an error how do I remove it? I'm new to programming, so I use these repositories for knowledge

**Comment by jahirfiquitiva** [comment]
what do you want to remove?

**Comment by Joseiltonslv** [comment]
there's an app that I was looking at the files, and I found this library (piracychecker) so I was testing if I can remove and leave the app working, even in apk

**Comment by jahirfiquitiva** [comment]
that's beyond the purposes of the library, therefore we don't provide support for that, sorry
