### ISSUE TITLE
AIDL Deprecated

### ISSUE THREAD

**Issue by DaXmYsT** [javiersantos/PiracyChecker#106]
Hello, first of all thank you for your nice work.

 I´ve got one question:

Like Google mentioned AIDL is now deprecated, see e.g.: https://developer.android.com/google/play/billing/migrate

Are there any plans to update your Libary to a non AIDL Version?

Best Regards, 
Dennis

**Comment by jahirfiquitiva** [comment]
Hi

This is probably a confusion because the AIDL we use in this library is meant for licensing, not billing, and if you look deeper, we don't really use much of AIDL.

Therefore, you don't need to worry.

**Comment by DaXmYsT** [comment]
Ok, thank you. :)
