### ISSUE TITLE
Add a simple check for LuckyPatcher (& similar) package names for an extra layer of security

### ISSUE THREAD

**Issue by franciscofranco** [javiersantos/PiracyChecker#14]
You can also do something like in this post: https://forum.xda-developers.com/showpost.php?p=65125064&postcount=102

Then saving a key->value to the default shared preferences file making sure that even if the user has uninstalled LuckyPatcher that the app is still going to fail.

**Comment by javiersantos** [comment]
Hi @jahirfiquitiva. I have released the v1.0 update.

```Javascript
dependencies {
    compile 'com.github.javiersantos:PiracyChecker:1.0'
}
```

It includes a method to block the app even when the pirate app has been uninstalled. See the [README](https://github.com/javiersantos/PiracyChecker#verify-the-use-of-pirate-apps) for more details.

Thank you!
