### ISSUE TITLE
Status bar icons are barely visible on Display.ACTIVITY

### ISSUE THREAD

**Issue by franciscofranco** [javiersantos/PiracyChecker#18]
![031317235554](https://cloud.githubusercontent.com/assets/792248/23879997/b2ceceda-0848-11e7-9afe-b46bc788379a.png)

**Comment by franciscofranco** [comment]
You can apply LightStatusBar on >= api 24 and leave the statusbar black for below. Or make set statusBarColor as #33000000

**Comment by javiersantos** [comment]
Currently, Display.ACTIVITY will use your main `android:theme` style. So, if a NoActionBar style is provided it will be displayed like your screenshot.

I plan to release a new update in the coming days to solve this. Toolbar will be included in the Activity and the user will be able to customize it with his own colors.

**Comment by javiersantos** [comment]
https://github.com/javiersantos/PiracyChecker/releases/tag/1.0.2
