### ISSUE TITLE
I think to make to more Secure Library should apply check in JNI......otherwise its cool library

### ISSUE THREAD

**Issue by Farrukh381** [javiersantos/PiracyChecker#20]
-its Just a suggestion

**Comment by franciscofranco** [comment]
Of course it'll be almost bullet proof, but working with JNI is a whole different monster. I for one have no fond memories of such thing...

**Comment by javiersantos** [comment]
I agree with you. Working with JNI would be awesome, but I think it's not a possible implementation in the short-term.
