### ISSUE TITLE
Using the library, makes my app crash on its very first use.

### ISSUE THREAD

**Issue by jahirfiquitiva** [javiersantos/PiracyChecker#21]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests.
- [x] I have verified that I am using the latest version of PiracyChecker.
- [x] I have given my issue a non-generic title.
- [x] I have read over the documentation (before asking questions on how to do something).

###### Details
 - PiracyChecker version: `1.0.2`
 - Device OS version: `7.1.1`
 - Device Manufacturer: `All`
 - Device Name: `All`

###### Information

So, when I enable the license check in my app, it causes a weird crash but it only happens the very first time I use the app.

All the logs say is:
```
channel 'cf4caaf pl.patrykgoworowski.cornieicons/jahirfiquitiva.iconshowcase.activities.ShowcaseActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
```
and
```
RemoteException caught trying to send a callback msg for NetworkRequest [ LISTEN id=12, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED] ]
```

Can you please share some help about it?  Thanks in advance.

**Comment by franciscofranco** [comment]
I'm having the same issue.

**Comment by franciscofranco** [comment]
I had to roll back to 1.0.1 otherwise the FC happened every time on first app use. The Exception is the only thing I could salvage, no other information anywhere.

**Comment by jahirfiquitiva** [comment]
@franciscofranco 
The problem with that version is that some Samsung devices are recognized as emulators and also there's no way to destroy the license checker so one does not get exceptions like `Activity has leaked ServiceConnection`

@javiersantos 
I don't know, but could this have something to do with the new support library 25.3.0 ? Would you mind giving a try at going back to 25.2.0 just for testing?
In one of my apps, version 25.3.0 started causing a crash for something that never crashed on previous versions.

**Comment by franciscofranco** [comment]
Yes 1.0.1 has a couple issues which 1.0.2 fixes, but the FC kills it. Dunno about the support lib, but it's a possibility.

**Comment by jahirfiquitiva** [comment]
@franciscofranco 
I'm going to fork this again and try a couple things, because @javiersantos seems to be busy.

**Comment by javiersantos** [comment]
Thank you @jahirfiquitiva.

https://github.com/javiersantos/PiracyChecker/releases/tag/1.1

**Comment by imspikey** [comment]
@jahirfiquitiva  please can you reopen this issue as I am facing the same problem in many devices although I am using the latest version 1.2.5!!?
