### ISSUE TITLE
How to get APK signature for the PRODUCTION

### ISSUE THREAD

**Issue by complitech** [javiersantos/PiracyChecker#27]
Hello, Can anybody suggest how to get APK signature for the PRODUCTION?

**Comment by javiersantos** [comment]
Add this line to your `MainActivity` (for example) and then compile the app with your production signature.

```Java
Log.e("SIGNATURE", PiracyCheckerUtils.getAPKSignature(this));
```

Install the generated APK and the signature will be showed in the Logcat. Don't forget to remove the previous line!
