### ISSUE TITLE
Create a null debug version

### ISSUE THREAD

**Issue by johngray1965** [javiersantos/PiracyChecker#28]
First off, Thanks for PricaryChecker.   Once I add PiracyChecker, I can't debug my app without wrapping the code with a if  BuildConfig.DEBUG.  But that gives hook for disabling PiracyChecker (some of crackers are looking things if'd off with BuildConfig.DEBUG).  It would easy enough to make release and debug version, I think it just mean moving one class in src/release/java and copy of it that's stripped in src/debug/java.  Then the gradle lines are changed to:
    releaseCompile 'com.github.javiersantos:PiracyCheckerRelease:1.1'
    debugCompile 'com.github.javiersantos:PiracyCheckerDebug:1.1'

No hook for anything to grab onto.  The release build will always have it, the deubg will always be disabled.

I'm happy to make a PR for this if there's interest.

**Comment by jahirfiquitiva** [comment]
I think if you are willing to make a PR for this, you should totally do it. @javiersantos will merge it when he thinks it's ok to do so. :)

**Comment by yuger** [comment]
This repo must be run on UI thread, otherwise throw a Native Exception.
backtrace:
  #00  pc 0000000000005b90  /system/lib/libGLESv1_CM.so (glGetString+60)
  #01  pc 0000000072478b3d  /data/dalvik-cache/arm/system@framework@boot.oat
...

**Comment by javiersantos** [comment]
Sure, feel free to do so. I'm going to close the issue for now, if there's any news, I'll open it again.
