### ISSUE TITLE
README omission?

### ISSUE THREAD

**Issue by drmrbrewer** [javiersantos/PiracyChecker#33]
Should the README mention the need for the CHECK_LICENSE permission in the Manifest?

**Comment by javiersantos** [comment]
As the permission is included in the library's AndroidManifest, it is automatically merged into the main manifest: https://developer.android.com/studio/build/manifest-merge.html

**Comment by drmrbrewer** [comment]
OK thanks.  Particularly a big thanks for making this library available.
