### ISSUE TITLE
License always fails

### ISSUE THREAD

**Issue by Alikaraki95** [javiersantos/PiracyChecker#36]
- [X] I have verified there are no duplicate active or recent bugs, questions, or requests.
- [X] I have verified that I am using the latest version of PiracyChecker.
- [X] I have given my issue a non-generic title.
- [X] I have read over the documentation (before asking questions on how to do something).

###### Details
 - PiracyChecker version: `1.2`
 - Device OS version: `8.0.0`
 - Device Manufacturer: `Xiamo`
 - Device Name: `Mi A1`

###### Builder
```Java
new PiracyChecker(this)
   .enableGooglePlayLicensing("XXXX")
                //.enableInstallerId(InstallerID.GOOGLE_PLAY)
                .enableSigningCertificate("XXXXX")// The original APK signature for the PRODUCTION version
                .enableUnauthorizedAppsCheck()
                .saveResultToSharedPreferences(mpref, "valid_license")
                .enableDebugCheck()
                .display(Display.ACTIVITY);
   .start();
```

###### Reproduction Steps

1.
2.
3.

###### Expected Result
License success

###### Actual Result
License fail

**Comment by Alikaraki95** [comment]
I added google license and its always failing, whenever i remove it/Comment it it works. I double checked my key from API developer console and it's still failing. Any ideas ?

**Comment by javiersantos** [comment]
Your APK must be submitted to Google Play, otherwise the verification will fail. Have you uploaded the APK that you are testing to Google Play?

**Comment by Alikaraki95** [comment]
yeah it's already uploaded and published, i commented the piracy check section since it was failing. Right now, i only enabled installer_ID for the paid version of my app. I'm trying to make it work again now.

I want to know something, my app has Google Play signing enabled, does it affect it in anyway ?

**Comment by Alikaraki95** [comment]
What i've seen from this, if you have google sign enabled ( after you upload to Google console ), signing check will fail. I disabled it and the method works fine, just wanted to point that out.

**Comment by javiersantos** [comment]
That's a good point, thank you for letting me know @Alikaraki95. Google Play App Signing removes the original signature and add another one, so it becomes invalid. I will update the README.

**Comment by kavanmevada** [comment]
@Alikaraki95 here is the fix 
https://medium.com/@kavanmevada/signing-certificate-verification-from-android-app-d50339f868d9

I hope GooglePlayLicensing will also work again in your Privacy Checker [just mention a person]
