### ISSUE TITLE
LuckyPatcher 7.0.8 not recognized

### ISSUE THREAD

**Issue by Asama1** [javiersantos/PiracyChecker#40]
Got it from lucky patchers website. It's version as 7.0.8 and ends with .COIN
Can you add it please?

**Comment by jahirfiquitiva** [comment]
Can you please share the whole package? Because there's already one with .COIN included 🤔

**Comment by javiersantos** [comment]
*Version:* 7.0.8 (1478)
*Package:* com.android.vending.billing.InAppBillingService.COIN

**Comment by jahirfiquitiva** [comment]
@javiersantos 
Isn't it added already [here](
https://github.com/javiersantos/PiracyChecker/blob/master/library/src/main/java/com/github/javiersantos/piracychecker/LibraryUtils.java#L311)

**Comment by javiersantos** [comment]
@jahirfiquitiva Yes, but the update hasn't been released yet.

**Comment by javiersantos** [comment]
https://github.com/javiersantos/PiracyChecker/releases/tag/1.2.1

**Comment by Asama1** [comment]
Can't we have a custom method to add packages manually? 
This way we won't have to update the lib for each package change. Would be really helpful to have something like addCustomPackage("package") 😁

**Comment by javiersantos** [comment]
That would be a very interesting feature. I've created a new issue for that.
