### ISSUE TITLE
Add method to check unauthorized custom apps

### ISSUE THREAD

**Issue by javiersantos** [javiersantos/PiracyChecker#41]
As requested by @Osama1 on #40, it would be interesting to add a `addCustomPackage("package")` method for detecting unauthorized packages.

**Comment by jahirfiquitiva** [comment]
This has been added in my last commit. I'll let you check and create the release if you want to :)

**Comment by javiersantos** [comment]
I just created a new release. Thank you!

https://github.com/javiersantos/PiracyChecker/releases/tag/1.2.2
