### ISSUE TITLE
google play console report 

### ISSUE THREAD

**Issue by boostermbkking** [javiersantos/PiracyChecker#44]
- PiracyChecker version: `1.2.2` & '1.2.3'
 - Device OS version: `8.0`

Google report Policy Issue: Your app was rejected for violating our [Device and Network Abuse policy](https://play.google.com/intl/it/about/privacy-security-deception/device-network-abuse/) and sections [4.8](https://play.google.com/about/developer-distribution-agreement.html#use) and [4.9](https://play.google.com/about/developer-distribution-agreement.html#prohibited) of the Developer Distribution Agreement.

I'm not able to release my app with piracychecker, developer console reject any update if I not remove this Piracychecker, please fix this issue

**Comment by jahirfiquitiva** [comment]
This is the very first time I know of someone getting an app rejected while using this library, and I know a lot of apps that use this.

Now, some questions:
1. Are you adding the internet permissions to your AndroidManifest.xml?
2. Are you adding the check license permissions to your AndroidManifest.xml?
3. Are you sure you're not filling your app with a bunch of ads and blaming this library?

**Comment by boostermbkking** [comment]
1- 2 yes I add internet and check license permissions
3 never used ads or other library/api

**Comment by jpvs0101** [comment]
This looks awkward! 😕
Because I also planning to release new app along with this library!
Now have to recheck....

**Comment by javiersantos** [comment]
I am not sure that the cause of the rejection is the library, basically because it is not even using the INTERNET permission.

Could it be related to the recent changes of GPRD?

**Comment by ItzNotABug** [comment]
I use this library in all of my Apps, never got a Rejection or a Suspension...

**Comment by ZonaRMR** [comment]
I have included Piracy Checker in my recent app and everything works fine. No rejection, no problem with Google Play,
