### ISSUE TITLE
License check not working on Play Store 10.7

### ISSUE THREAD

**Issue by piereligio** [javiersantos/PiracyChecker#46]
- [v] I have verified there are no duplicate active or recent bugs, questions, or requests.
- [v] I have verified that I am using the latest version of PiracyChecker.
- [v] I have given my issue a non-generic title.
- [v] I have read over the documentation (before asking questions on how to do something).

###### Details
 - PiracyChecker version: `any`
 - Device OS version: `any`
 - Device Manufacturer: `any`
 - Device Name: `any`

###### Builder
https://github.com/substratum/template/blob/kt-n/app/src/main/kotlin/substratum/theme/template/SubstratumLauncher.kt
[line 64 to 100]

###### Reproduction Steps

1. Update play store to 10.7
2. Try to open app

###### Expected Result
License check doing its work letting the user in

###### Actual Result
License check won't check the license successfully, and the user will be blocked out.
Don't know if happens on any kind of apps, I am a substratum theme developer.

**Comment by jahirfiquitiva** [comment]
I think you must fill the issue template properly.

1. Are you sure it happens using any PiracyChecker version?
2. Are you sure it happens on any device OS version?

3. The code snippet:
```java
new PiracyChecker(this)
   ...
   .start();
```

Doesn't really tell us how you are using PiracyChecker, so we can know if it's you who's doing something wrong or it's the library.

Please update the issue template accordingly, with relevant and accurate information, otherwise this issue will be closed and ignored.

**Comment by gcantoni** [comment]
@jahirfiquitiva https://issuetracker.google.com/issues/110978499

**Comment by piereligio** [comment]
Okay, fixed by linking the class from Substratum repository. Here is an issue tracker about the problem.
https://issuetracker.google.com/issues/110978499

**Comment by jahirfiquitiva** [comment]
It definitely is a fault on Google Play Store, taken into account it only happened after updating it, and it's already reported by multiple developers in the Google Issue Tracker ... let's hope they get it fixed soon, but there's really nothing we can do for now.

**Comment by piereligio** [comment]
Thank you for the feedback. At least now we have reliable information from the source.
