### ISSUE TITLE
Not working on Xiaomi and Moto Devices

### ISSUE THREAD

**Issue by akshaykumar04** [javiersantos/PiracyChecker#51]
Not working on Moto and Xiaomi devices!

###### Details #1
 - PiracyChecker version: `1.2.3`
 - Device OS version: `7.0.0`
 - Device Manufacturer: `Moto`
 - Device Name: `G4 Plus`

###### Details #2
 - PiracyChecker version: `1.2.3`
 - Device OS version: `7.1.1`
 - Device Manufacturer: `Xiaomi`
 - Device Name: `Note 5 Pro`

###### Builder
private void verify() {
        checker = new PiracyChecker(this)
                    .enableGooglePlayLicensing("MY_KEY")
                    checker.start();
    }

######Result
Working on my Nexus 5 (7.1.1)

###### Actual Result
Not working on these 2 devices I've tested so far

**Comment by jahirfiquitiva** [comment]
You're probably setting up something wrong. Also, post logs that can help us identify what is causing the issue. Simply saying "Does not work on X device" won't help, because we might not have _**that**_ specific device to test
