### ISSUE TITLE
New Logo/Icon proposal

### ISSUE THREAD

**Issue by mansya** [javiersantos/PiracyChecker#52]
Good day sir. I am a graphic designer and i am interested in designing a logo for your good project. I will be doing it as a gift for free. I just need your permission first before I begin my design. Hoping for your positive feedback. Thanks

**Comment by jahirfiquitiva** [comment]
Hi
I don't think we need a logo or icon right now, and I am honestly tired of seeing random users create (and spam with) random issues in random repositories about logos or icons.
I'm going to close this for that reason. I'll let @javiersantos to decide if it's really needed or not

**Comment by mansya** [comment]
ok no problem.

**Comment by javiersantos** [comment]
We don't really need an icon for a library. Thank you anyway.
