### ISSUE TITLE
How to disable PiracyChecker when developing?

### ISSUE THREAD

**Issue by saipsa** [javiersantos/PiracyChecker#59]
Normally I would do

```
  if(!BuildConfig.DEBUG)
        {
            checkForPiracy();
        }
```

But disabling it for Debug build will render the `                .enableDebugCheck(true)
` useless.

**Comment by jahirfiquitiva** [comment]
If you're debugging it yourself, you don't need any checks, so your initial code will be just fine

**Comment by saipsa** [comment]
@jahirfiquitiva what if someone else is running it in debug mode?

**Comment by jahirfiquitiva** [comment]
@saipsa 
Well, you will have to be sure of the people you share the debug flavor app.

If you're making it public, use a release flavor always.

**Comment by saipsa** [comment]
@jahirfiquitiva Then the check `.enableDebugCheck(true)` is to prevent accidental sharing of debug flavor? I don't think so.

**Comment by jahirfiquitiva** [comment]
@saipsa
It is to prevent people from recompiling the app in debug mode and sharing it without your permission

**Comment by saipsa** [comment]
@jahirfiquitiva then if I have disabled piracycheck in debug mode, it doesn't prevent  people from recompiling the app in debug mode, does it?

**Comment by jahirfiquitiva** [comment]
@saipsa Unfortunately no.
You can never prevent people from recompiling the app, unless you enable the signature checks.
But even then pirates will find a way.

There's simple not a real way one can provide a 100% secure app.
