### ISSUE TITLE
How to create Trial version

### ISSUE THREAD

**Issue by webserveis** [javiersantos/PiracyChecker#6]
Is posible use this library for add in apps , similar system of "trial version 30 days"

**Comment by MrOutis** [comment]
I would use server side checking for this; it depends on your app's needs.

If your users login to use your app, you can add a field on your database indicating the first login, then, you can check if 30 days have elapsed (the trial version) before sending the "authorized" response.

This app helps more to prevent copying the .apk into another phone.

**Comment by javiersantos** [comment]
You can implement a trial version using `SharedPreference`, but I don't recommend this option to you because it can be modified easily (even encrypting the preferences). Server side would be the best option, as @MrOutis said (using Firebase, for example).
