### ISSUE TITLE
  error: failed linking references.

### ISSUE THREAD

**Issue by marwanzak** [javiersantos/PiracyChecker#60]
I have a problem after adding dependency and sync

Android resource linking failed
Output:  /Users/marwan/Documents/Android-Projects/photogo/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-v28/values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
/Users/marwan/Documents/Android-Projects/photogo/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-v28/values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
/Users/marwan/Documents/Android-Projects/photogo/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:1590: error: resource android:attr/fontVariationSettings not found.
/Users/marwan/Documents/Android-Projects/photogo/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:1591: error: resource android:attr/ttcIndex not found.
error: failed linking references.

Command: /Users/marwan/.gradle/caches/transforms-1/files-1.1/aapt2-3.2.0-4818971-osx.jar/76c130dc24c69748b151c0483251f08a/aapt2-3.2.0-4818971-osx/aapt2 link -I\
        /Users/marwan/Library/Android/sdk/platforms/android-27/android.jar\
        --manifest\
        /Users/marwan/Documents/Android-Projects/photogo/app/build/intermediates/merged_manifests/debug/processDebugManifest/merged/AndroidManifest.xml\
        -o\
        /Users/marwan/Documents/Android-Projects/photogo/app/build/intermediates/processed_res/debug/processDebugResources/out/resources-debug.ap_\
        -R\
        @/Users/marwan/Documents/Android-Projects/photogo/app/build/intermediates/incremental/processDebugResources/resources-list-for-resources-debug.ap_.txt\
        --auto-add-overlay\
        --java\
        /Users/marwan/Documents/Android-Projects/photogo/app/build/generated/not_namespaced_r_class_sources/debug/processDebugResources/r\
        --proguard-main-dex\
        /Users/marwan/Documents/Android-Projects/photogo/app/build/intermediates/legacy_multidex_aapt_derived_proguard_rules/debug/processDebugResources/manifest_keep.txt\
        --custom-package\
        net.kayisoft.photogo\
        -0\
        apk\
        --output-text-symbols\
        /Users/marwan/Documents/Android-Projects/photogo/app/build/intermediates/symbols/debug/R.txt\
        --no-version-vectors
Daemon:  AAPT2 aapt2-3.2.0-4818971-osx Daemon #0

How could I solve it?

**Comment by jahirfiquitiva** [comment]
Be sure to use Support Libraries v 28.0.0 and not use AndroidX libs
