### ISSUE TITLE
not working for me

### ISSUE THREAD

**Issue by Hugsoft** [javiersantos/PiracyChecker#62]
- [x ] I have verified there are no duplicate active or recent bugs, questions, or requests.
- [x ] I have verified that I am using the latest version of PiracyChecker.
- [ x] I have given my issue a non-generic title.
- [x ] I have read over the documentation (before asking questions on how to do something).

###### Details
 - PiracyChecker version: `1.2.4`
 - Device OS version: `7.1.1`
 - Device Manufacturer: `MIUI`
 - Device Name: `REDMI NOTE 4`

  new PiracyChecker(this)
     .enableGooglePlayLicensing("i_added_here_my_BASE_64_LICENSE_KEY")
    .enableSigningCertificate("i_added_here_my_signin_key")
     .display(Display.ACTIVITY)
                .start();

i used signin key which shows in log
and base key from store

when i try app
it show only error that app is not sign try from valid source.
i uploaded as beta tester for app still same error. please help

is while debug app sign in key is different from app in beta tester and release apk?

**Comment by jahirfiquitiva** [comment]
Hey...

Of course you have to use the release apk signing key. They are indeed different.

Give it a try and let us know

**Comment by Hugsoft** [comment]
i created a release apk and used that signed key but same activity is poping up.

**Comment by jahirfiquitiva** [comment]
@Hugsoft try clearing app data and cache

**Comment by Hugsoft** [comment]
first i have to release in play store than i have to note down sign key then add that key , after that re release that apk?

**Comment by jahirfiquitiva** [comment]
1. Prepare your code to print the signing key in logcat or somewhere in the app.
2. Export a release apk signed with your desired key.
3. Install it manually in your device and get that key.
4. Edit your code to remove the code that prints the signing key.
5. Continue working with your app and when ready, do a release to play store.

Note: this won't work if you registered in the new signing program by Play Store. They generate a random key and you won't have access to it.
