### ISSUE TITLE
Password for SimpleUnauthorizedApp.zip ?

### ISSUE THREAD

**Issue by GSharma789** [javiersantos/PiracyChecker#65]

**Comment by javiersantos** [comment]
Why do you need the password? It is only used by Travis for automatic testing purposes.

**Comment by GSharma789** [comment]
We can also test locally if we have such demo app . If you can please share password

**Comment by javiersantos** [comment]
I'm sorry, but that file is only used for internal testing of the library. If you need to test a pirate app (Lucky Patcher, Freedom, CreeHack, etc) you will have to download it on your own and modify the Travis file (just remove the `unzip` line and place the APK on the root of the project).
