### ISSUE TITLE
Inadequate Documentation

### ISSUE THREAD

**Issue by Edge-Developer** [javiersantos/PiracyChecker#66]
Is there a sample App and a detailed behavior of what will happen when the conditions aren't met. The current documentation is inadequate.

What will be shown/happen per case bases?

Some gif or a youtube tutorial would go a long way.

Thanks!

**Comment by jahirfiquitiva** [comment]
I don't understand your request. Everything is explained in the readme. You can also create custom callbacks so you have all control over what will be shown or what will happen when license check fails or succeeds (being valid or invalid), etc. 🤔😕🤷🏻‍♂️

**Comment by jahirfiquitiva** [comment]
If you have specific questions, just ask

**Comment by javiersantos** [comment]
I think the documentation is well explained. The library blocks the use of the app in case of detecting an invalid license, among other methods.

You can also check the sample app : https://github.com/javiersantos/PiracyChecker/tree/master/app

I will close this issue for now.
