### ISSUE TITLE
False detection of invalid licence and signature

### ISSUE THREAD

**Issue by drmrbrewer** [javiersantos/PiracyChecker#67]
I have just added PiracyChecker to my app, and for the vast majority of cases it seems to be detecting a valid licence and signature.  

But for a very small number of cases, it is detecting `NOT_LICENSED` and `SIGNATURE_NOT_VALID` even though I'm fairly sure that the users are genuine (they have been in contact, and provided the Play Store purchase confirmation).  

Something in common between two of those affected is that they have a Xiaomi Redmi Note running Android 9.  At least one of these is devices rooted, and I believe that the Android 9 OS from Xiaomi is a beta version.

I'm initiating the licence and signature checks just with a basic method as per the docs, i.e. `.enableGooglePlayLicensing(myKey)` and `.enableSigningCertificate(mySig)` with a `.callback()` to set a custom shared pref based on the result.

As I said, for the vast majority of cases, this works fine, so the basic method I'm using seems OK (i.e. I haven't got it completely wrong, with a failed check every time)... it's just some users.

Is this a known problem with some devices?  I find it difficult to understand how the signature check can fail, in particular.

**Comment by jahirfiquitiva** [comment]
Are you using Google Play App Signing service?

**Comment by drmrbrewer** [comment]
No.

**Comment by drmrbrewer** [comment]
I think what I'm seeing may be the result of something else going on in my code.  I'll look into this further, and close this issue for now.
