### ISSUE TITLE
Library conflicts with other libraries when using Kotlin

### ISSUE THREAD

**Issue by bjarn** [javiersantos/PiracyChecker#68]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests.
- [x] I have verified that I am using the latest version of PiracyChecker.
- [x] I have given my issue a non-generic title.
- [x] I have read over the documentation (before asking questions on how to do something).

###### Details
 - PiracyChecker version: `1.2.5`
 - Device OS version: `n/a`
 - Device Manufacturer: `n/a`
 - Device Name: `n/a`

###### Builder
```Kotlin
            piracyChecker {
                enableGooglePlayLicensing(APP_PUBLIC_KEY.reversed())
                display(Display.ACTIVITY)
            }.start()
```

###### Reproduction Steps

1. Implement the library and another library with a module named 'library'.
2. Build the app in Android Studio
3. Wait until the error pops up

###### Expected Result
The build should succeed.

###### Actual Result
The error message that is being thrown by Gradle is:
More than one file was found with OS independent path 'META-INF/library_release.kotlin_module'

A fix for this will be renaming the project. See: https://readyset.build/build-failures-kotlin-metadata-errors-f0090cdf948c

**Comment by jahirfiquitiva** [comment]
Add this to your `app/build.gradle` file:

```gradle
android {
  ...
  packagingOptions {
    pickFirst 'META-INF/core_debug.kotlin_module'
    pickFirst 'META-INF/core_release.kotlin_module'
    pickFirst 'META-INF/library_debug.kotlin_module'
    pickFirst 'META-INF/library_release.kotlin_module'
  }
  ...
}

**Comment by bjarn** [comment]
Thanks a lot! Seems to have fixed the issue.

**Comment by jahirfiquitiva** [comment]
Good to know!
