### ISSUE TITLE
java.security.spec.InvalidKeySpecException

### ISSUE THREAD

**Issue by AhmedX6** [javiersantos/PiracyChecker#69]
Hello,

When passing a random key for google licensing I have : java.security.spec.InvalidKeySpecException: com.android.org.conscrypt.OpenSSLX509CertificateFactory$ParsingException: Error parsing public key. Please could you fix that bug ?

Thanks

**Comment by jahirfiquitiva** [comment]
you must use the key Google provides in the services section of the developer console

**Comment by AhmedX6** [comment]
Yes of course,

But it will be better to catch the error, because for now it crahs.

Thanks

**Comment by jahirfiquitiva** [comment]
No, it cannot be simply catch because:
a) the key is wrong and or invalid
b) you need to know there's an issue with your key
c) if we simply ignore it, you would still blame us because license check won't work at all
