### ISSUE TITLE
Gradle dependency

### ISSUE THREAD

**Issue by fillobotto** [javiersantos/PiracyChecker#7]
Hi,
I'm trying to add this library through Gradle.build file:

> dependencies {
>     compile 'com.github.javiersantos:PiracyChecker:0.0.2'
> }

Syncing Gradle will result in dependency not found error

**Comment by javiersantos** [comment]
Have you added the Jitpack repository to your project `build.gradle`? 

```gradle
repositories {
    maven {
        url "https://jitpack.io"
    }
}
```

Have a look to the [sample project](https://raw.githubusercontent.com/javiersantos/PiracyChecker/master/build.gradle) too.

**Comment by fillobotto** [comment]
What a cheek I've been...
