### ISSUE TITLE
Ability to customize activity & display logs

### ISSUE THREAD

**Issue by avipars** [javiersantos/PiracyChecker#70]
I would like to add links to the activity, so users can e-mail me a log of why the app thinks they are a pirate. 
Right now, through the custom XML, I figured out a fix, but I need to link directly and display the whole URL to the user. It would be awesome if I could customize the activity via java or kotlin too.

I am also getting tens or requests a day, and need something to prove to them that they store the app, or a solution, so they can use it again. If there is a way that I could log exactly where the piracy checker caught them, it would be amazing!

**Comment by jahirfiquitiva** [comment]
We aim to keep the custom dialog or activity simple

You can simply create your very own activity and deal with the license check results by [implementing a callback](https://github.com/javiersantos/PiracyChecker#using-custom-callbacks)

It will give you details about the license check error and the app that was found and considered as pirate.
