### ISSUE TITLE
Disable titlebar of custom layout activity

### ISSUE THREAD

**Issue by imarindam** [javiersantos/PiracyChecker#75]
Hello, 
Thank you for developing this awesome and useful library.
I want to mention that this is not a bug report, it is a request. 
My app follow NoActionBar style all over the app. I have enabled `.withActivityLayout(R.layout.my_custom_layout)` as recommended and also as it is necessary for my app. 
But the titlebar text is not what looks good there as my app has unique logo as title.
Hence, it is my request can you please let me know how to disable the titebar for the activity?

**Comment by jahirfiquitiva** [comment]
You can simply use the callback function to launch your very own activity with the layout and styles you actually want

**Comment by imarindam** [comment]
@jahirfiquitiva Thank you for clarification.
