### ISSUE TITLE
Can provide unauthorised app list from json url

### ISSUE THREAD

**Issue by akashefrath** [javiersantos/PiracyChecker#95]
How i can give unauthorised app. List from a json url any idea. Please guide me

**Comment by jahirfiquitiva** [comment]
Unfortunately such feature is not available and there are currently no plans to include it

**Comment by akashefrath** [comment]
Okey bro.. But i see some apps have this future.. Adn I can't add more then one app its also got error

**Comment by jahirfiquitiva** [comment]
You can already [add more apps](https://github.com/javiersantos/PiracyChecker#add-custom-apps-to-check) to be checked as explained in the readme: https://github.com/javiersantos/PiracyChecker#add-custom-apps-to-check

Plus, you are welcome to contribute to the project by adding them to the default apps list

**Comment by akashefrath** [comment]
When i add more apps i got error like thia

**Comment by jahirfiquitiva** [comment]
that's because the constructor accepts 2 parameters only: name and package name. You have to repeat that for every app you want to add
